### ISSUE TITLE
add-ons or addons ?

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/kinto2xml#13]
In my current Gecko patch, I had `addons`.

**Comment by Natim** [comment]
Refs https://github.com/mozilla-services/amo-blocklist-ui/issues/40

**Comment by leplatrem** [comment]
Okay, so since kinto-admin uses the collection name in the menu, it was decided to rename it to `add-ons`. We should probably add an issue in kinto-admin to read like a `label` attribute in the collection object instead.

I'll update my patch on Gecko to `add-ons` anyway.

**Comment by Natim** [comment]
> https://github.com/mozilla-services/amo-blocklist-ui/issues/40

:confused: :sorry:

**Comment by leplatrem** [comment]
Actually, I realized the code was already landed in Gecko with `addons`: https://dxr.mozilla.org/mozilla-central/search?q=addons.collection

**Comment by Natim** [comment]
So what do we do about that?

**Comment by tarekziade** [comment]
If "addons" was pushed in gecko,  let's use "addons" everywhere at this point.

If the goal of "add-on" is for the UI, I think that's now down to having the ability to have labels attached to collection names in kinto-admin
