### ISSUE TITLE
Amazon Lambda

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/kinto2xml#20]
The scripts will run on Lambda. Let's make sure it works, or if it needs some tweaking let's do them

**Comment by tarekziade** [comment]
http://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html

**Comment by Natim** [comment]
I have created kinto2xml-lambda to address this: https://github.com/mozilla-services/kinto2xml-lambda
